version: 0.2

phases:
  build:
    commands:
      - mvn install
artifacts:
  files:
    - files/*
    - target/suchapp-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - start.sh
    - stop.sh
    - test_app.service
cache:
  paths:
    - '/root/.m2/**/*'
