- hosts: localhost
  vars:
    app_name: TestApp
    aws_region: eu-west-1
    ssh_key_name: my_key
    ssh_key_value: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCod03I5wxFGU5OW7jYBcyGIb70NOPuYRR7N
      ejVtBXI+C0cVa9hG21PRj424ZwknU3MPJe1DjyT/a1S85oh7USr/FY1RI6RqdEKPYuhhc0pqP
      QnWFsDzQ1gq9odvcUDUGVeSFXtA4WlHhZZIPKoPgKU0cx0Bjq61aUVjzEERlTthgN9+QBMt+M
      7GCoKPZx90vA27z6CrGSfoe6EVqDmK1AcqCBLN6huyirI4jAZxS8kbTZ+6LyzEzA8Xx6fklIl
      DR3vdLZ49D6Phc/U3RFJO4ookV4UwJZ6mPHIbEz1Go3Mlu/+hiG8Cn4ZRk6Uv3Pcc2qmlg0Lo
      /lUdlkgOc9MVEl9 m@debi
    github_repo_owner: monester
    github_repo_name: opstest
    github_repo_branch: enchance_vpc_security
    github_token: "{{ lookup('env','GITHUB_TOKEN') }}"
  tasks:
    - name: create ssh key
      ec2_key:
        name: "{{ ssh_key_name }}"
        key_material: "{{ ssh_key_value }}"
        force: true
        state: present
        region: "{{ aws_region }}"

    - name: create articact storage
      s3_bucket:
        name: test-app-artifacts
        region: "{{ aws_region }}"

    - name: Application code pipeline
      cloudformation:
        stack_name: "{{app_name}}Pipeline"
        state: "present"
        region: "{{ aws_region }}"
        template: "files/codepipeline.yaml"
        template_parameters:
          ApplicationName: "{{ app_name }}"
          ArtifactS3Bucket: "test-app-artifacts"
          GitHubOwner: "{{ github_repo_owner }}"
          GitHubRepo: "{{ github_repo_name }}"
          GitHubBranch: "{{ github_repo_branch }}"
          GitHubToken: "{{ github_token }}"
